language: node_js

branches:
  except:
    - master

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: www.zvecr.com
  keep_history: true
  local_dir: dist
  target_branch: master
  on:
    branch: develop
